// XML-to-JSON processor. Dynamically imported by ./dropzone.client.js
// (routed by #tool's data-client="xmlToJson") on first file selection/
// paste-convert click, or warmed on pointerenter/focus -- same lazy-load
// reasoning as ./sortLines.client.js. This tool has two input paths that
// both land here as the same File shape: a .xml file chosen/dropped
// through the normal drop zone, or XML text typed into the "paste XML"
// text box (dropzone.client.js wraps the pasted text in a synthetic File
// before calling this module's run(), so this file never needs to know
// which path a given File came from).
//
// Parsing uses the browser's own DOMParser in 'application/xml' mode --
// the same mode ../browser/xlsxToCsv.client.js already uses for the XML
// parts inside an .xlsx archive, not a new dependency. That file's header
// comment already states the load-bearing security fact this tool relies
// on too: browsers do not resolve external entities/DTDs for a
// DOMParser-parsed document (no XXE surface), and the parsed document is
// inert (scripting disabled, per
// https://html.spec.whatwg.org/#dom-domparser-parsefromstring) and never
// attached to this page's live DOM. That fact is re-verified here, not
// just assumed, by test/xmlToJson.security.e2e.test.mjs -- a real
// Playwright/Chromium test that points a hostile external-entity payload
// at a logging "attacker" server and asserts zero requests ever arrive,
// mirroring test/htmlTableToCsv.security.e2e.test.mjs's own empirical
// check for its own DOMParser use.
//
// This tool's own threat model is wider than xlsxToCsv's, though: an
// .xlsx's internal XML parts are always machine-generated by Excel (or a
// compatible writer), never handed to this tool directly by an untrusted
// third party the way a visitor's own pasted/dropped XML is here -- a
// visitor can paste ANY XML, including one with a <!DOCTYPE> declaring
// custom entities. Browsers don't fetch an EXTERNAL entity/DTD (see
// above), but an INTERNAL entity (defined inside the document's own
// <!DOCTYPE ... [ ... ]> internal subset, no network fetch needed) can
// still reference itself recursively -- the classic "billion laughs"
// pattern -- and cause runaway memory use in the VISITOR'S OWN TAB while
// being parsed, entirely locally. Rather than lean on a specific engine's
// entity-expansion limits (undocumented, and not something this site
// controls or can re-verify per browser release), this tool refuses ANY
// XML containing a <!DOCTYPE> outright, before the text is ever handed to
// DOMParser -- see ../pure/xmlToJson.mjs's containsDoctype(). That closes
// off both the external-entity and the internal-entity-expansion risk by
// construction, at the cost of not supporting the (for this tool's actual
// use case -- converting a document to JSON -- vanishingly rare) case of
// XML that legitimately needs a custom-entity DOCTYPE, which gets a clear
// refusal message rather than a silent hang or a crashed tab.
//
// The actual element-to-JSON-value shaping is pure and lives in
// ../pure/xmlToJson.mjs so it stays unit-testable without a DOM; this
// file's job is only to (a) read the File's text, (b) call DOMParser and
// walk its result into the plain-data node shape that module expects (see
// domElementToPlainNode below), (c) render the read-only JSON preview,
// and (d) build/download the .json file.
//
// Any text pulled out of the XML (tag names, attribute values, text
// content) is untrusted visitor content and is only ever written via
// .textContent (through renderResult's use of pre.textContent for the
// whole JSON string), never interpolated into an HTML string -- same rule
// every other tool here follows.

const PREVIEW_CHAR_LIMIT = 200000;

function downloadBlob(blob, filename) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 10000);
}

function jsonBlob(jsonText) {
  return new Blob([jsonText], { type: 'application/json;charset=utf-8' });
}

/**
 * Walks a parsed, still-detached DOMParser Element into the plain-data
 * shape ../pure/xmlToJson.mjs's nodeToJsonValue() expects (its own header
 * comment documents the exact shape) -- nodeType 1 (element) recurses,
 * nodeType 3/4 (text/CDATA) become a text child, nodeType 7/8 (processing
 * instruction/comment) are dropped (see that module's header for why).
 *
 * @param {Element} el
 * @returns {import('../pure/xmlToJson.mjs').PlainXmlNode}
 */
function domElementToPlainNode(el) {
  const attrs = Array.from(el.attributes || []).map((a) => [a.name, a.value]);
  const children = Array.from(el.childNodes)
    .map((n) => {
      if (n.nodeType === 1) return { type: 'element', node: domElementToPlainNode(n) };
      if (n.nodeType === 3 || n.nodeType === 4) return { type: 'text', text: n.nodeValue };
      return null;
    })
    .filter(Boolean);
  return { tag: el.tagName, attrs, children };
}

/**
 * Renders the stats badge, the read-only JSON preview, and the download
 * button. Called once per run() -- like ../browser/jsonToCsv.client.js and
 * ../browser/yamlToJson.client.js this tool has no per-visitor option
 * toggles.
 *
 * @param {HTMLElement} resultEl
 * @param {string} jsonText the full, pretty-printed JSON text.
 */
function renderResult(resultEl, jsonText) {
  resultEl.innerHTML = '';

  const block = document.createElement('div');
  block.className = 'table-block';

  const head = document.createElement('div');
  head.className = 'table-block-head';
  const badge = document.createElement('span');
  badge.className = 'page-badge';
  const lineCount = jsonText.split('\n').length;
  badge.textContent = `${lineCount} line${lineCount === 1 ? '' : 's'} of JSON`;
  head.appendChild(badge);
  block.appendChild(head);

  const pre = document.createElement('pre');
  pre.className = 'json-preview';
  const truncated = jsonText.length > PREVIEW_CHAR_LIMIT;
  pre.textContent = truncated ? `${jsonText.slice(0, PREVIEW_CHAR_LIMIT)}\n…` : jsonText;
  block.appendChild(pre);

  if (truncated) {
    const previewNote = document.createElement('p');
    previewNote.className = 'caption';
    previewNote.textContent = 'Showing the first part of the result. The download includes all of it.';
    block.appendChild(previewNote);
  }

  const btnRow = document.createElement('div');
  btnRow.className = 'download-btn-row';
  const downloadBtn = document.createElement('button');
  downloadBtn.type = 'button';
  downloadBtn.className = 'btn-primary';
  downloadBtn.textContent = 'Download converted.json';
  downloadBtn.addEventListener('click', () => {
    downloadBlob(jsonBlob(jsonText), 'converted.json');
  });
  btnRow.appendChild(downloadBtn);
  block.appendChild(btnRow);

  const supportNote = document.createElement('p');
  supportNote.className = 'support-note';
  supportNote.innerHTML = 'That ran entirely on your machine - no servers, no cost to run. If it saved you time, you can buy me a coffee: '
    + '<a href="https://ko-fi.com/flavaa" target="_blank" rel="noopener noreferrer">Ko-fi</a>'
    + ' &middot; '
    + '<a href="https://buymeacoffee.com/dylanger254" target="_blank" rel="noopener noreferrer">Buy Me a Coffee</a>.';
  block.appendChild(supportNote);

  resultEl.appendChild(block);
  resultEl.hidden = false;
}

function showError(resultEl, setState, setStatus, message) {
  resultEl.innerHTML = '';
  const msg = document.createElement('div');
  msg.className = 'alert alert-warn';
  msg.setAttribute('role', 'alert');
  msg.textContent = message;
  resultEl.appendChild(msg);
  resultEl.hidden = false;
  setState('error');
  setStatus(message, 'error');
}

/**
 * @param {{files:File[], resultEl:Element, setState:Function, setStatus:Function}} ctx
 */
export async function run(ctx) {
  const { files, resultEl, setState, setStatus } = ctx;
  const file = files[0];
  setState('working');
  setStatus('Reading that file on this device…');

  const { containsDoctype, documentToJsonValue, formatXmlParseError } = await import('../pure/xmlToJson.mjs');

  const text = await file.text();

  if (!text.trim()) {
    showError(resultEl, setState, setStatus, 'That’s empty - paste or drop some XML first.');
    return;
  }

  if (containsDoctype(text)) {
    showError(
      resultEl,
      setState,
      setStatus,
      'That XML has a <!DOCTYPE> declaration, which this tool doesn’t process (custom entities there can’t be resolved safely in every browser). Remove the <!DOCTYPE ...> line and try again.'
    );
    return;
  }

  const doc = new DOMParser().parseFromString(text, 'application/xml');
  const errEl = doc.querySelector('parsererror');
  if (errEl || !doc.documentElement) {
    const friendly = formatXmlParseError(errEl ? errEl.textContent : '');
    showError(resultEl, setState, setStatus, friendly);
    return;
  }

  const rootNode = domElementToPlainNode(doc.documentElement);
  const jsonValue = documentToJsonValue(rootNode);
  const jsonText = JSON.stringify(jsonValue, null, 2);

  resultEl.innerHTML = '';
  renderResult(resultEl, jsonText);

  setState('done');
  setStatus('Converted. Review below, then download.', 'success');
}
